ecom_dwh:
  outputs:
    dev:
      dataset: ecom_dwh
      job_execution_timeout_seconds: 100
      job_retries: 1
      keyfile: W:\work\Projects\real-time_DE_project\ecommerce-etl-pipeline\databricks_notebooks\clientLibraryConfig-databricks-gcp-provider.json
      location: US
      method: service-account
      priority: interactive
      project: batch-processing-de
      threads: 2
      type: bigquery
  target: dev
