ecom_dwh:
  outputs:
    dev:
      dataset: ecom_dwh_dbt
      job_execution_timeout_seconds: 100
      job_retries: 1
      keyfile: ./gcp_sa_key.json
      location: US
      method: service-account
      priority: interactive
      project: batch-processing-de
      threads: 2
      type: bigquery
  target: dev
