# models/sources.yml
version: 2

sources:
  - name: ecom_dwh
    #database: batch-processing-de
    database: ecom_dwh
    tables:
      - name: fact_daily_sales
      - name: dim_products
      - name: dim_customers # Assuming this is also loaded by Spark